name = "PitchAnalysis"
uuid = "9d8583ba-e503-4469-a0b3-ef382289a639"
version = "0.1.0"
authors = ["andymalv <73136243+andymalv@users.noreply.github.com>"]

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
DSP = "0.8.4"
DataFrames = "1.8.1"
Debugger = "0.7.16"
Infiltrator = "1.9.4"
JSON = "1.3.0"
LinearAlgebra = "1.12.0"
